services:

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: pea_laravel
    volumes:
      - ./env/laravel.env:/var/www/html/.env:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pea-laravel.rule=Host(`api-pea.dev-fullstack.net`)"
      - "traefik.http.routers.pea-laravel.entrypoints=websecure"
      - "traefik.http.routers.pea-laravel.tls.certresolver=myresolver"
    networks:
      - antibes

  nuxt:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NUXT_PUBLIC_SANCTUM_BASE_URL: https://api-pea.dev-fullstack.net
    container_name: pea_nuxt
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.pea-nuxt.rule=Host(`pea.dev-fullstack.net`)"
    - "traefik.http.routers.pea-nuxt.entrypoints=websecure"
    - "traefik.http.routers.pea-nuxt.tls.certresolver=myresolver"
    networks:
      - antibes
    depends_on:
      - laravel

networks:
  antibes:
    external: true
    name: antibes
