name: Deploy Nuxt Frontend

on:
  push:
    tags:
      - 'frontend-v*'  # ex: frontend-v1.0.0

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ghcr.io/jeremieflahaut/pea/nuxt
  VERSION_TAG: ${{ github.ref_name }}
  SHA_TAG: sha-${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Nuxt image
        run: |
          docker build -t $IMAGE_NAME:latest \
                       -t $IMAGE_NAME:${VERSION_TAG} \
                       -t $IMAGE_NAME:${SHA_TAG} ./frontend
          docker push $IMAGE_NAME --all-tags

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /home/debian/projects/pea
            docker compose -f docker-compose.prod.yml pull nuxt
            docker compose -f docker-compose.prod.yml up -d nuxt
