name: Run Laravel Tests

on:
  pull_request:
    branches:
      - main

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, bcmath, pdo_sqlite, sqlite3
          coverage: none

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest --optimize-autoloader

      - name: Prepare environment file
        run: cp .env.testing .env

      - name: Create SQLite database file if it doesn't exist
        run: |
          if [ ! -f database/database-testing.sqlite ]; then
            touch database/database-testing.sqlite
          fi

      - name: Generate application key
        run: php artisan key:generate

      - name: Run database migrations
        run: php artisan migrate --no-interaction --force

      - name: Run tests with Pest
        run: ./vendor/bin/pest
